name: Windows(VisualStudio 2019)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install numpy
      run: python3 -m pip install numpy
        
    - name: Install matplotlib
      run: |
        python3 -m pip install matplotlib
        
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}\build -G "Visual Studio 16 2019" -A x64

    - name: Build
      run: cmake --build ${{github.workspace}}\build --config ${{env.BUILD_TYPE}}
      
